# Generated by Django 5.1.1 on 2024-09-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cajaDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.IntegerField(verbose_name='Saldo inicial')),
                ('saldo_final', models.IntegerField(verbose_name='Saldo final')),
                ('ingreso_totales', models.IntegerField(verbose_name='Ingreso totales')),
                ('gasto_totales', models.IntegerField(verbose_name='Gasto total')),
                ('nota', models.TextField(max_length=75, verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='ClienteDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=15, verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('direccion', models.CharField(max_length=70, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='inventarioDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=25, verbose_name='Nombre Producto')),
                ('stock_disponible', models.IntegerField(verbose_name='Stock disponible')),
                ('precio_inventario', models.IntegerField(verbose_name='Precio Inventario')),
                ('estado', models.BooleanField(verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='metodo_pagoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_metodo_pago', models.CharField(max_length=25, verbose_name='Nombre Metodo de pago')),
            ],
            options={
                'verbose_name': 'Metodo_pago',
                'verbose_name_plural': 'Metodo_pagos',
                'db_table': 'Metodo_pagos',
            },
        ),
        migrations.CreateModel(
            name='cajeroDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_cajero', models.CharField(max_length=25, verbose_name='Nombre Cajero')),
                ('turno_cajero', models.CharField(max_length=25, verbose_name='Turno cajero')),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionSistema.cajadb')),
            ],
            options={
                'verbose_name': 'Cajero',
                'verbose_name_plural': 'Cajeros',
                'db_table': 'Cajeros',
            },
        ),
        migrations.CreateModel(
            name='TransacionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateField(blank='False', verbose_name='fecha y hora')),
                ('tipo_transacional', models.CharField(max_length=25, null='False', verbose_name='Tipo de transaccion')),
                ('subtotla', models.IntegerField(verbose_name='subtotal')),
                ('inpuesto', models.IntegerField(verbose_name='inpuesto')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('descripcion_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionSistema.metodo_pagodb')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionSistema.clientedb')),
            ],
            options={
                'verbose_name': 'transacion',
                'verbose_name_plural': 'Transaciones',
                'db_table': 'Transaciones',
            },
        ),
        migrations.CreateModel(
            name='reporte_ventaDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_venta', models.IntegerField(verbose_name='Total Venta')),
                ('fecha_reporte', models.DateTimeField(verbose_name='Fecha Reoporte')),
                ('id_transacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionSistema.transaciondb')),
            ],
            options={
                'verbose_name': 'Reporte_venta',
                'verbose_name_plural': 'Reportes_ventas',
                'db_table': 'Reportes_Ventas',
            },
        ),
        migrations.CreateModel(
            name='reporte_devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_devolucion', models.IntegerField(verbose_name='Monto de devoluciones')),
                ('fecha_reporte_devoluciones', models.DateField(verbose_name='Fecha Devolucion')),
                ('id_transacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionSistema.transaciondb')),
            ],
            options={
                'verbose_name': 'Reporte_devolucion',
                'verbose_name_plural': 'Reportes_Devoluciones',
                'db_table': 'Reportes_Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Detalle_transacionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto', models.CharField(max_length=30, null='False', verbose_name='Descripcion del producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio unitario')),
                ('decuento', models.IntegerField(verbose_name='Descuento')),
                ('id_transacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionSistema.transaciondb')),
            ],
            options={
                'verbose_name': 'Detalle_transacion',
                'verbose_name_plural': 'detalles_transaciones',
                'db_table': 'Detalles_transaciones',
            },
        ),
        migrations.CreateModel(
            name='datos_fiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc_cliente', models.CharField(max_length=15, verbose_name='RCN Cliente')),
                ('detalles_inpuesto', models.IntegerField(verbose_name='Detalles Inpuesto')),
                ('id_transacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionSistema.transaciondb')),
            ],
            options={
                'verbose_name': 'Datos_fiscale',
                'verbose_name_plural': 'Datos_Fiscales',
                'db_table': 'Datos_Fiscales',
            },
        ),
    ]
