# Generated by Django 5.1.1 on 2024-09-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionSistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='metodo_pagoDb',
            new_name='MetodoPagoDb',
        ),
        migrations.RenameField(
            model_name='transaciondb',
            old_name='subtotla',
            new_name='subtotal',
        ),
    ]
